version: 2
jobs:
  build: # job name
    docker:
      - image: circleci/node:10.2.1
      # The secondary container is an instance of the second listed image which is run in a common network where ports exposed on the primary container are available on localhost.

    working_directory: ~/repo
    # The primary container is an instance of the first image listed. The job's commands run in this container.

    steps:
      - checkout

      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}

      - run:
          name: Install dependencies with NPM
          command: npm install

      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - node_module

      - run:
          name: TS Build
          command: npm run tsc

      - run:
          name: Build src with NPM
          command: npm run build

workflows:
  version: 2
  Build and Test:
    jobs:
      - build
